Increase user-friendliness of short of assets error (closes #104)
stellar/kelp pull request #492
Opened 2020-08-28 20:16 UTC by debnil

This PR increases the user-friendliness of the error when short of assets. This closes #104.

2020-08-29 12:31 UTC, nikhilsaraf requested changes
let me know if you have any questions.

2020-08-29 12:31 UTC, nikhilsaraf commented on plugins/sellSideStrategy.go
> -		return 0, 0, fmt.Errorf("error: (programmer?) unable to create offer but available capacities were more than the attempted offer amounts, sellingCapacity=%.8f, incrementalSellAmount=%.8f, buyingCap
I think this old error message is correct. See the if condition -- it should always hold true. If it is false then it means something has gone terribly wrong and it's likely a programmer error as indicated by the error message.

IIRC this error has always occurred whenever there were less assets in the user's account so this error message was only a red herring.

There is another error message that indicates that the user has less assets. Search for the following in `ieif.go`:
`we will oversell`

There are two occurrences of that message, we should leave those two error messages as-is and add this additional line to hint to the user the corrective action they need to take:
```
utils.PrintErrorHintf("Your account may have run out of the asset '%s'. Add more tokens of '%s' so the bot can run correctly")
```

You will need to reproduce this issue to confirm that it is working correctly. Once fixed, could you please upload the section of the log file (between the two separator lines `--------`) when the user has a low balance for a bot trading (a) SOME_ASSET_A vs XLM where XLM is low; and (b) market trading with SOME_ASSET_A vs. SOME_ASSET_B where XLM is low and it is unable to pay fees?

2020-08-29 17:02 UTC, debnil commented
@nikhilsaraf: Got it, thanks!! Would you be able to write e steps to reproduce the ieif.go error on the original issue, just to make sure we're on the same page?

2020-08-29 17:18 UTC, nikhilsaraf commented
Added some details on the issue. Let me know if that helps or we can discuss on Monday too.

2020-08-31 05:32 UTC, debnil commented
Those are super helpful. I'm just going to close this PR - the changes are super different, and this way, I can contribute from a fork rather than a branch pushed to `master`.

2020-08-31 05:32 UTC, closed without merging